// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "user": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/microservice-registration/design
// --out=$(GOPATH)src/github.com/JormungandrK/microservice-registration
// --version=v1.2.0-dirty

package app
